language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install coveralls

install:
  - pip install Django==${DJANGO}
  - pip install -e .
  - pip install -r requirements-test.txt

script: make test

env:
  - DJANGO=1.11.27
  - DJANGO=2.0.13
  - DJANGO=2.1.15
  - DJANGO=2.2.9
  - DJANGO=3.0.2

matrix:
  exclude:
    - python: 3.8
      env: DJANGO=1.11.27
    - python: 2.7
      env: DJANGO=2.0.13
    - python: 3.8
      env: DJANGO=2.0.13
    - python: 2.7
      env: DJANGO=2.1.15
    - python: 3.4
      env: DJANGO=2.1.15
    - python: 3.8
      env: DJANGO=2.1.15
    - python: 2.7
      env: DJANGO=2.2.9
    - python: 3.4
      env: DJANGO=2.2.9
    - python: 2.7
      env: DJANGO=3.0.2
    - python: 3.4
      env: DJANGO=3.0.2
    - python: 3.5
      env: DJANGO=3.0.2

after_success:
  - coveralls
