language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

before_install:
  - pip install coveralls

install:
  - pip install Django==${DJANGO}
  - pip install -e .
  - pip install -r requirements-test.txt

script: make test

env:
  - DJANGO=1.11.15
  - DJANGO=2.0.8
  - DJANGO=2.1

after_success:
  - coveralls
